### ISSUE TITLE
Cargo Folders

### ISSUE THREAD

**Issue by Davnik** [HeavensGate/Eternal#132]
Place two folders on the QM's Office Desk, and one folder by the stamps at the Cargo Front Desk.

**Comment by CitationNeeded** [comment]
Done. Please close this.

**Comment by Davnik** [comment]
That doesn't appear to be the case. Cargo Shutters also wasn't resolved, and I suspect #149 wasn't merged.

**Comment by killer99603** [comment]
The folders are done. Checking shutters thing.

**Comment by woothie** [comment]
Killer's on a rampage! :D
